---

- name: create ~/.aws directory
  when:
    - not running_in_check_mode
  become: true
  no_log: true
  ansible.builtin.file:
    path: "{{ item.value.home | default('/home') }}/{{ item.key }}/.aws"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    state: directory
    mode: "0700"
    force: false
  loop: "{{ awscli_users | dict2items }}"
  loop_control:
    label: "{{ item.value.home | default('/home') }}/{{ item.key }}/.aws"

- name: create AWS CLI config file
  when:
    - not running_in_check_mode
    - item.value.profiles is defined
  become: true
  no_log: true
  register: changed_config_files
  ansible.builtin.template:
    src: "{{ awscli_config }}"
    dest: "{{ item.value.home | default('/home') }}/{{ item.key }}/.aws/config"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: "0600"
    force: true
  loop: "{{ awscli_users | dict2items }}"
  loop_control:
    label: "{{ item.value.home | default('/home') }}/{{ item.key }}/.aws/config"
  notify:
    - changed config files

- name: create AWS CLI credentials file
  when:
    - not running_in_check_mode
    - item.value.profiles is defined
  become: true
  no_log: true
  register: changed_credentials_files
  ansible.builtin.template:
    src: "{{ awscli_credentials }}"
    dest: "{{ item.value.home | default('/home') }}/{{ item.key }}/.aws/credentials"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: "0600"
    force: true
  loop: "{{ awscli_users | dict2items }}"
  loop_control:
    label: "{{ item.value.home | default('/home') }}/{{ item.key }}/.aws/credentials"
  notify:
    - changed credentials files

- name: flush handlers
  when:
    - not running_in_check_mode
  ansible.builtin.meta: flush_handlers

...
