---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yaml
      skip: true

- name: define delegate instance for download handling
  set_fact:
    awscli_delegate_to: "{{ ansible_host }}"
    awscli_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/awscli', true) }}/{{ awscli_version }}"
  when:
    - awscli_direct_download

- name: get latest tags
  block:
    - name: get github tags
      uri:
        url: "https://api.github.com/repos/aws/aws-cli/tags"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      # no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _github_tag
      until: _github_tag.status == 200
      retries: 5

    - name: set awscli version to {{ _github_tag.json.tag_name[1:] }}
      set_fact:
        awscli_version: "{{ _github_tag.json.tag_name[1:] }}"
  when:
    - awscli_version == "latest"

- name: install python3-apt
  block:
    - name: make sure python3-apt is installed (only debian based)
      package:
        name:
          - python3-apt
        state: present
      register: _installed

    - name: clean apt cache
      command: apt-get clean
      args:
        warn: false
      when:
        - _installed.changed

    - name: update package cache
      package:
        update_cache: true
      when:
        - _installed.changed
  when:
    - ansible_os_family | lower == 'debian'

- name: detect if awscli {{ awscli_version }} is present
  stat:
    path: "/usr/local/bin/aws_{{ awscli_version }}"
  register: awscli_versioned_installed

- name: define installed aws-cli version
  awscli_version:
    validate_version: "{{ awscli_version }}"
  register: awscli_installed_version
  check_mode: false
  ignore_errors: true

- name: create download directory
  become: false
  delegate_to: "{{ awscli_delegate_to }}"
  file:
    path: "{{ awscli_local_tmp_directory }}"
    state: directory
    mode: "0750"
  when:
    - awscli_versioned_installed is defined
    - not awscli_versioned_installed.stat.exists

- name: define uninstall awscli
  set_fact:
    awscli_uninstall: "{{ awscli_installed_version.version.major is version_compare(awscli_version.split('.') | first, '<') }}"
  when:
    - awscli_installed_version is defined
    - awscli_installed_version.version is defined
    - awscli_installed_version.version.major is defined

- name: define reinstall awscli
  set_fact:
    awscli_reinstall: "{{ awscli_installed_version.full_version is version_compare(awscli_version, '!=') }}"
  when:
    - awscli_installed_version is defined
    - awscli_installed_version.version is defined
    - awscli_installed_version.version.major is defined

- name: update package cache
  package:
    update_cache: true

- name: install dependencies
  package:
    name: "{{ awscli_dependencies }}"
    state: present

- name: python support
  block:
    - name: create requirements.txt
      template:
        src: requirements.txt.j2
        dest: /tmp/awscli-requirements.txt
        mode: "0660"

    - name: ensure python dependecies for awscli are installed
      pip:
        requirements: /tmp/awscli-requirements.txt
        state: present
        executable: pip{{ '3' if ansible_python.version.major | int == 3 else '' }}
      register: pip_install
      # ignore_errors: true
      # no_log: true

  when:
    - awscli_python_packages is defined
    - awscli_python_packages | count > 0

...
